services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    ports:
      - 5432:5432
  portaria:
    build: ./
    ports:
      - 3000:3000
