services:
  portaria:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    networks:
      - minha-rede
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    networks:
      - minha-rede
networks:
  minha-rede:
