services:
  postgres_db:
    image: postgres
    restart: no
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    cpus: "0.2"
    mem_limit: 512m
    networks:
      - minha-rede
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    build: ./backend/
    restart: no
    environment:
      - POSTGRES_URL=postgres://admin:admin@postgres_db:5432/app
      - JWT_SECRET=dcdf8a0fe31a9ba779f152d022e2bf072622ece0
    ports:
      - 3001:3001
    cpus: "0.2"
    mem_limit: 512m
    volumes:
      - ./backend/:/usr/src/app
    depends_on:
      - postgres_db
    networks:
      - minha-rede
  frontend:
    build: ./frontend/
    restart: no
    environment:
      - EXPRESS_URL=http://backend:3001
      - AUTH_SECRET=dPq15u8ofTVLRLCWl+D0l1bFl50mO38XDfxsLPvkJtQ=
      - AUTH_URL=http://localhost:3000/api/auth
    ports:
      - 3000:3000
    cpus: "0.6"
    mem_limit: 1g
    volumes:
      - ./frontend/:/usr/src/app
    depends_on:
      - backend
      - postgres_db
    networks:
      - minha-rede
networks:
  minha-rede:
