services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    networks:
      - minha-rede
  portaria:
    build: ./
    environment:
      - POSTGRES_URL=postgres://admin:admin@postgres_db:5432/app
      - AUTH_SECRET=dPq15u8ofTVLRLCWl+D0l1bFl50mO38XDfxsLPvkJtQ=
      - AUTH_URL=http://localhost:3000/api/auth
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres_db
    networks:
      - minha-rede
networks:
  minha-rede:
